### ISSUE TITLE
Could you upgrade libavif to v0.6.0?

### ISSUE THREAD

**Issue by ledyba-z** [SDWebImage/SDWebImageAVIFCoder#15]
Could you upgrade https://github.com/AOMediaCodec/libavif ?

It needs to close #12 

Note that there is a breaking change in v0.6.0, and it is not compatible to v0.5.7.

**Comment by dreampiggy** [comment]
The libavif-Xcode have a subspec dependency of [librav1e](https://github.com/SDWebImage/librav1e-Xcode)

The previous version of librav1e-Xcode use the Git LFS to hold the binary library.

However, it's now run out of the free bandwith (1GB per repo). So the new `pod trunk push` will fail because the Git LFS is not available. (CocoaPods can not push without passing the lint for all the subspecs combination)

I'm try to migrate to use GitHub release or Bintray service insead. Please wait, thanks :)

**Comment by dreampiggy** [comment]
@ledyba-z Done.

The rav1e CocoaPods, now use the GitHub Release instead of Git LFS...I spent 2 hours to implements the automation release via Travis CI. This can save me from update and build locally.

See: https://github.com/SDWebImage/librav1e-Xcode/releases, a framework zip can be downloaded via CocoaPods && Carthage.

The libavif now already update to 0.6.0, which use the dependency of librav1e 0.3.0+.


```
➜  librav1e-Xcode git:(master) pod trunk info libavif

libavif
    - Versions:
      - 0.1.0 (2019-04-14 15:24:55 UTC)
      - 0.1.1 (2019-04-29 03:04:59 UTC)
      - 0.1.2 (2019-04-29 03:27:18 UTC)
      - 0.1.3 (2019-04-29 03:30:00 UTC)
      - 0.1.4 (2019-08-21 07:05:30 UTC)
      - 0.2.0 (2019-08-21 07:46:39 UTC)
      - 0.3.0 (2019-10-07 18:54:15 UTC)
      - 0.3.11 (2019-10-08 05:50:31 UTC)
      - 0.4.0 (2019-10-08 06:39:28 UTC)
      - 0.4.1 (2019-10-30 16:33:29 UTC)
      - 0.4.2 (2019-10-30 16:55:57 UTC)
      - 0.4.3 (2019-10-31 15:40:10 UTC)
      - 0.4.4 (2019-10-31 16:00:45 UTC)
      - 0.4.5 (2020-01-19 12:39:55 UTC)
      - 0.4.6 (2020-01-19 12:53:08 UTC)
      - 0.4.7 (2020-01-19 14:13:02 UTC)
      - 0.4.8 (2020-01-19 17:51:08 UTC)
      - 0.5.0 (2020-01-21 01:48:45 UTC)
      - 0.5.1 (2020-01-21 01:56:15 UTC)
      - 0.5.2 (2020-01-21 02:02:48 UTC)
      - 0.5.3 (2020-01-21 02:10:14 UTC)
      - 0.5.4 (2020-01-23 05:36:18 UTC)
      - 0.5.5 (2020-03-04 07:30:40 UTC)
      - 0.5.6 (2020-03-04 08:18:30 UTC)
      - 0.5.7 (2020-03-04 08:29:38 UTC)
      - 0.6.0 (2020-03-11 05:22:07 UTC)
    - Owners:
      - DreamPiggy <lizhuoli1126@126.com>
      - Bogdan Poplauschi <bpoplauschi@gmail.com>

➜  librav1e-Xcode git:(master) pod trunk info librav1e

librav1e
    - Versions:
      - 0.1.0 (2019-10-31 14:35:18 UTC)
      - 0.1.0-beta (2019-10-31 15:15:03 UTC)
      - 0.2.0 (2020-01-24 04:49:58 UTC)
      - 0.3.0 (2020-03-11 04:43:16 UTC)
      - 0.3.1 (2020-03-11 06:35:30 UTC)
    - Owners:
      - DreamPiggy <lizhuoli1126@126.com>
      - Bogdan Poplauschi <bpoplauschi@gmail.com>
```
